In [5]:
from price_comparer.price_comparer import PriceComparer
from datetime import datetime

In [13]:
date = datetime.now().strftime("%d_%m_%Y")
date

'23_04_2025'

In [14]:
old_file_date = "14_04_2025"
new_file_date = "23_04_2025"

In [15]:
old_file_path = f"C:/Users/derkv/OneDrive/Documenten/Brightminds/Webscraper/result_data/result_{old_file_date}.xlsx"
new_file_path = f"C:/Users/derkv/OneDrive/Documenten/Brightminds/Webscraper/result_data/result_{new_file_date}.xlsx"

In [16]:
comparer = PriceComparer(old_file_path, new_file_path)
diff, new_rows, removed_rows = comparer.run()

In [18]:
diff.to_excel(f"C:/Users/derkv/OneDrive/Documenten/Brightminds/Webscraper/comparison_data/{new_file_date}_diff_to_{old_file_date}.xlsx", index = False)

In [12]:
diff

,product_name,pet,brand,size,quantity_package,quantity_package_unit,quantity_ordered,price_medpets_old,price_medpets_new,is_owned_medpets_old,is_owned_medpets_new,num_competitors_old,num_competitors_new,avg_price_old,avg_price_new,diff_from_competitors_old,diff_from_competitors_new
0,hond|milbemax|L (5 - 25kg)|2.0 tabl,hond,milbemax,L (5 - 25kg),2.0,tabl,1,11.05,11.25,<NA>,<NA>,NaN,NaN,10.4500,10.500000,NaN,NaN
1,hond|milbemax|L (5 - 25kg)|4.0 tabl,hond,milbemax,L (5 - 25kg),4.0,tabl,1,20.95,19.50,<NA>,<NA>,NaN,NaN,19.7825,19.420000,-2.8325,-2.470000
2,hond|milbemax|S (0 - 5kg)|4.0 tabl,hond,milbemax,S (0 - 5kg),4.0,tabl,1,NaN,NaN,False,True,3.0,4.0,8.4400,8.567500,-0.4900,-0.617500
3,hond|seresto|S (< 8 kg)|2.0 pack,hond,seresto,S (< 8 kg),2.0,pack,1,NaN,NaN,False,True,3.0,4.0,65.9100,64.845000,NaN,NaN
4,"hond|vectra|XS (1,5 - 4 kg)|3.0 pip",hond,vectra,"XS (1,5 - 4 kg)",3.0,pip,1,21.95,22.75,<NA>,<NA>,NaN,NaN,21.9500,22.216667,-2.4500,-2.716667